[package]
name = "cpr-blockchain-poc"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]

[dependencies]
wasmi = "0.4.2"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
