[package]
name = "common"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[features]
default = []
std = []

[dependencies]
blake2 = { version = "0.8", default-features = false }
byteorder = { version = "1", default-features = false }
wee_alloc = "0.4.2"
